# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171014_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '密码找回'), ('update', '修改邮箱')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
