# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_courseorg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='谁知道呢', max_length=10, verbose_name='机构标签'),
        ),
    ]
