# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='课程类别'),
        ),
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='章节数'),
        ),
    ]
