# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20171014_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresourse',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to='course/resouce/%Y/%m', verbose_name='资源文件'),
        ),
    ]
