# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20171014_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_known',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='tell_you',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='老师告诉你什么'),
        ),
    ]
